### ISSUE TITLE
Initial Development PRs need to be closed out

### ISSUE THREAD

**Issue by christinahedges** [PandoraMission/exoscraper#9]
The development PRs we put in when we did our Python parties need to be finished and either merged in or closed. @benhord can you take a look at these and decide what the right way forward is? 

#6 and #7 are the PRs that we need to look at

**Comment by benhord** [comment]
Yes! I'll take a look at these remaining PRs and determine what to do with them.

**Comment by benhord** [comment]
This has now been completed!
